set.seed(2022)

1 - pchisq(q = 10, df = 2)

chisq_tailprob_nis <- function(n) {
    # Step 1 samples from proposal density
    X <- rcauchy(n)

    # Step 2 Calculate the normalised importance weights vector
    X[X<=0] <- 0
    w.tilde <- (1 + X^2)*exp(-X/2)*(X > 0)
    w.star <- w.tilde/sum(w.tilde)

    # Step 3. Calculate the estimator
    p.t <- sum(w.star*(X>10))
    return(p.t)
}

samples <- c(100, 1000, 10000, 100000)
for (n in samples){
    ## print the tail probability
    print(chisq_tailprob_nis(n))
} 


# Part 2

r_mychisq_sir <- function(n, m){
    # Step 1. samples from proposal density
    Y <- rcauchy(m)

    # Step 2. Calculate the normlaised importance weights vector
    # cutting the negative values of X to be zero,
    # to prevent producing NaN in exp(-X/2)
    Y[Y <= 0] <- 0
    w.tilde <- (1 + Yˆ2)*exp(-Y/2)*(Y > 0)
    w.star <- w.tilde/sum(w.tilde)
    # Step 3. Calculate the estimator
    X <- sample(Y, size = n, replace = TRUE, prob = w.star)
    return(X)
}

par(lend = 1)
hist(mysample, nclass = 50, prob = T,
    xlab = "Values generated by SIR",
    main=" Simulated and Actual PDF of Chi-square(2)")
curve(dchisq(x, df = 2), add = T, lwd = 2, col = "red")
legend("topright", legend = c("Simulated pdf", "Actual pdf"),
    pt.bg = adjustcolor(c('grey', NA), alpha.f = .5), pt.cex = 2,
    col = c("black","red"), lwd = 2, lty = c(NA, 1), pch = c(22, NA), cex = 0.9)
